export const GreenHouseConfig = {
  key: 'greenhouse',
  regex:
    /^https?:\/\/(?:www\.)?(?:ixl\.com|boards\.greenhouse\.io|www\.oldmissioncapital\.com)\/[^/]+\/jobs?\/[^?&/]+/,
  commonSelector: `[class*='field']`,
  selectors: {
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    linkedIn_url: 'LinkedIn Profile',
    portfolio_url: 'Portfolio Link',
    position_title: 'Title',
    school_name: 'School',
    degree: 'Degree',
    major: 'Discipline|Major',
    other_url: `Other`,
    is_authorized_in_us: 'authorized to work|eligible to work',
    is_required_visa: 'visa',
    secondary_email: `Email Address`,
    secondary_phone: 'Phone Number',
    city: `City`,
    gender: `Gender`,
    ethnicity: `race`,
    is_veteran: 'Veteran Status',
    is_disabled: 'Disability Status',
  },
  major: 'education_discipline_',
  degree: 'education_degree_',
}
