export const iCIMSConfig = {
  key: 'icims',
  regex: /^https:\/\/([\w-]+)\.icims\.com\/jobs\/(\d+)\/[\w-]+\/(candidate)(?:\?.*)?$/,
  commonSelector: `div[class*="iCIMS_TableRow"]`,
  applyForJobButton: `a[title="Apply for this job online"]`,
  formEmail: `form[id="enterEmailForm"] input`,
  acceptCheckbox: `div[class="checkbox gdpr_wrapper no_space"]`,
  iframeSelector: `iframe[id="icims_content_iframe"]`,
  addMoreButton: 'a[role="button"]',
  educationButtonText: 'Add More (Education)',
  experienceButtonText: 'Add More (Work Experience)',
  selectors: {
    firstName: 'first name',
    lastName: 'last name',
    email: 'Email',
    phone: 'Number',
    linkedIn_url: `LinkedIn`,
    github_url: `GitHub`,
    portfolio_url: `Portfolio`,
    other_url: `Other`,
    is_authorized_in_us: 'authorized to work|eligible to work',
    is_required_visa: 'visa',
    secondary_email: `Email Address`,
    secondary_phone: 'Phone Number',
    city: `City`,
    gender: `gender`,
    ethnicity: `race`,
    is_veteran: 'veteran',
  },
}
