export const iCIMSConfig = {
  key: 'icims',
  regex: /https:\/\/([\w-]+)\.icims\.com\/jobs\/\d+\/\S+/,
  commonSelector: `div[class*="iCIMS_TableRow"]`,
  applyForJobButton: `a[title="Apply for this job online"]`,
  formEmail: `form[id="enterEmailForm"] input`,
  acceptCheckbox: `div[class="checkbox gdpr_wrapper no_space"]`,
  iframeSelector: `iframe[name="icims_content_iframe"]`,
  dropdownSelector: `div[class*="dropdown-container"]`,
  addMoreButton: 'a[role="button"]',
  educationButtonText: 'Add More (Education)',
  education: 'div[class*="iCIMS_CollectionContainer CandProfileFields.Education-"]',
  experience: 'div[class*="iCIMS_CollectionContainer rcf3211-"]',
  experienceButtonText: 'Add More (Work Experience)',
  selectors: {
    firstName: 'first name',
    lastName: 'last name',
    email: 'Email',
    phone: 'Number',
    linkedIn_url: `LinkedIn`,
    github_url: `GitHub`,
    portfolio_url: `Portfolio`,
    description: 'Description',
    position_title: 'Title',
    school_name: 'School',
    degree: 'Degree',
    major: 'Major',
    other_url: `Other`,
    is_authorized_in_us: 'authorized to work|eligible to work',
    is_required_visa: 'visa',
    secondary_email: `Email Address`,
    secondary_phone: 'Phone Number',
    city: `City`,
    gender: `gender`,
    ethnicity: `race`,
    is_veteran: 'veteran',
  },
}
