export const majors = [
  { id: 1, name: 'Accounting' },
  { id: 2, name: 'Actuarial Science' },
  { id: 3, name: 'Aerospace Engineering' },
  { id: 4, name: 'Anthropology' },
  { id: 5, name: 'Applied Mathematics' },
  { id: 6, name: 'Architecture' },
  { id: 7, name: 'Art' },
  { id: 1, name: 'Art History' },
  { id: 1, name: 'Astronomy' },
  { id: 1, name: 'Business Analytics' },
  { id: 1, name: 'Cell & Molecular Biology' },
  { id: 1, name: 'Chemical Engineering' },
  { id: 1, name: 'Chemistry' },
  { id: 1, name: 'Civil Engineering' },
  { id: 1, name: 'Coding School' },
  { id: 1, name: 'Cognitive Science' },
  { id: 1, name: 'Biochemistry' },
  { id: 1, name: 'Bioinformatics' },
  { id: 1, name: 'Biology' },
  { id: 1, name: 'Biomedical Engineering' },
  { id: 1, name: 'Business' },
  { id: 1, name: 'Communications' },
  { id: 1, name: 'Computer Engineering' },
  { id: 1, name: 'Computer Science' },
  { id: 1, name: 'Data Science' },
  { id: 1, name: 'Education' },
  { id: 1, name: 'Earth Science' },
  { id: 1, name: 'Economics' },
  { id: 1, name: 'Electrical Engineering' },
  { id: 1, name: 'English' },
  { id: 1, name: 'Entrepreneurship' },
  { id: 1, name: 'Environmental Engineering' },
  { id: 1, name: 'Environmental Science' },
  { id: 1, name: 'Film' },
  { id: 1, name: 'Finance' },
  { id: 1, name: 'Human Computer Interaction' },
  { id: 1, name: 'Human Resources' },
  { id: 1, name: 'Industrial Engineering' },
  { id: 1, name: 'Informatics' },
  { id: 1, name: 'Information Science' },
  { id: 1, name: 'Information Systems' },
  { id: 1, name: 'International Relations' },
  { id: 1, name: 'Mechanical Engineering' },
  { id: 1, name: 'Music' },
  { id: 1, name: 'Neuroscience' },
  { id: 1, name: 'Nursing' },
  { id: 1, name: 'Operations Research' },
  { id: 1, name: 'Petroleum Engineering' },
  { id: 1, name: 'Financial Engineering' },
  { id: 1, name: 'Forensic Science' },
  { id: 1, name: 'Gender Studies' },
  { id: 1, name: 'Geophysics' },
  { id: 1, name: 'Graphic Design' },
  { id: 1, name: 'History' },
  { id: 1, name: 'Hotel Administration' },
  { id: 1, name: 'Journalism' },
  { id: 1, name: 'Latin American Studies' },
  { id: 1, name: 'Linguistics' },
  { id: 1, name: 'Management Engineering' },
  { id: 1, name: 'Marketing' },
  { id: 1, name: 'Materials Science' },
  { id: 1, name: 'Mathematics' },
  { id: 1, name: 'Pharmacology' },
  { id: 1, name: 'Pharmacy' },
  { id: 1, name: 'Philosophy' },
  { id: 1, name: 'Physics' },
  { id: 1, name: 'Political Science' },
  { id: 1, name: 'Pre-dental' },
  { id: 1, name: 'Pre-law' },
  { id: 1, name: 'Pre-medical' },
  { id: 1, name: 'Product Design' },
  { id: 1, name: 'Psychology' },
  { id: 1, name: 'Public Policy' },
  { id: 1, name: 'Public Relations' },
  { id: 1, name: 'Religious Studies' },
  { id: 1, name: 'Robotics' },
  { id: 1, name: 'Urban Studies' },
  { id: 1, name: 'Veterinary Medicine' },
  { id: 1, name: 'Sociology' },
  { id: 1, name: 'Software Engineering' },
  { id: 1, name: 'Sports Management' },
  { id: 1, name: 'Statistics' },
  { id: 1, name: 'Supply Chain Management' },
  { id: 1, name: 'Theatre' },
  { id: 1, name: 'Undeclared' },
  { id: 1, name: 'Urban Studies' },
  { id: 1, name: 'Other/Not listed' },
]

export const degrees = [
  { id: 1, name: 'Bachelors' },
  { id: 1, name: 'Masters' },
  { id: 1, name: 'MBA' },
  { id: 1, name: 'PhD' },
  { id: 1, name: 'PharMD' },
  { id: 1, name: 'Associates' },
]
