export const majors = [
  { id: 1, name: 'Accounting' },
  { id: 2, name: 'Actuarial Science' },
  { id: 3, name: 'Aerospace Engineering' },
  { id: 4, name: 'Anthropology' },
  { id: 5, name: 'Applied Mathematics' },
  { id: 6, name: 'Architecture' },
  { id: 7, name: 'Art' },
  { id: 1, name: 'Art History' },
  { id: 1, name: 'Astronomy' },
  { id: 1, name: 'Business Analytics' },
  { id: 1, name: 'Cell & Molecular Biology' },
  { id: 1, name: 'Chemical Engineering' },
  { id: 1, name: 'Chemistry' },
  { id: 1, name: 'Civil Engineering' },
  { id: 1, name: 'Coding School' },
  { id: 1, name: 'Cognitive Science' },
  { id: 1, name: 'Biochemistry' },
  { id: 1, name: 'Bioinformatics' },
  { id: 1, name: 'Biology' },
  { id: 1, name: 'Biomedical Engineering' },
  { id: 1, name: 'Business' },
  { id: 1, name: 'Communications' },
  { id: 1, name: 'Computer Engineering' },
  { id: 1, name: 'Computer Science' },
  { id: 1, name: 'Data Science' },
  { id: 1, name: 'Education' },
  { id: 1, name: 'Earth Science' },
  { id: 1, name: 'Economics' },
  { id: 1, name: 'Electrical Engineering' },
  { id: 1, name: 'English' },
  { id: 1, name: 'Entrepreneurship' },
  { id: 1, name: 'Environmental Engineering' },
  { id: 1, name: 'Environmental Science' },
  { id: 1, name: 'Film' },
  { id: 1, name: 'Finance' },
  { id: 1, name: 'Human Computer Interaction' },
  { id: 1, name: 'Human Resources' },
  { id: 1, name: 'Industrial Engineering' },
  { id: 1, name: 'Informatics' },
  { id: 1, name: 'Information Science' },
  { id: 1, name: 'Information Systems' },
  { id: 1, name: 'International Relations' },
  { id: 1, name: 'Mechanical Engineering' },
  { id: 1, name: 'Music' },
  { id: 1, name: 'Neuroscience' },
  { id: 1, name: 'Nursing' },
  { id: 1, name: 'Operations Research' },
  { id: 1, name: 'Petroleum Engineering' },
  { id: 1, name: 'Financial Engineering' },
  { id: 1, name: 'Forensic Science' },
  { id: 1, name: 'Gender Studies' },
  { id: 1, name: 'Geophysics' },
  { id: 1, name: 'Graphic Design' },
  { id: 1, name: 'History' },
  { id: 1, name: 'Hotel Administration' },
  { id: 1, name: 'Journalism' },
  { id: 1, name: 'Latin American Studies' },
  { id: 1, name: 'Linguistics' },
  { id: 1, name: 'Management Engineering' },
  { id: 1, name: 'Marketing' },
  { id: 1, name: 'Materials Science' },
  { id: 1, name: 'Mathematics' },
  { id: 1, name: 'Pharmacology' },
  { id: 1, name: 'Pharmacy' },
  { id: 1, name: 'Philosophy' },
  { id: 1, name: 'Physics' },
  { id: 1, name: 'Political Science' },
  { id: 1, name: 'Pre-dental' },
  { id: 1, name: 'Pre-law' },
  { id: 1, name: 'Pre-medical' },
  { id: 1, name: 'Product Design' },
  { id: 1, name: 'Psychology' },
  { id: 1, name: 'Public Policy' },
  { id: 1, name: 'Public Relations' },
  { id: 1, name: 'Religious Studies' },
  { id: 1, name: 'Robotics' },
  { id: 1, name: 'Veterinary Medicine' },
  { id: 1, name: 'Sociology' },
  { id: 1, name: 'Software Engineering' },
  { id: 1, name: 'Sports Management' },
  { id: 1, name: 'Statistics' },
  { id: 1, name: 'Supply Chain Management' },
  { id: 1, name: 'Theatre' },
  { id: 1, name: 'Undeclared' },
  { id: 1, name: 'Urban Studies' },
  { id: 1, name: 'Other/Not listed' },
]

export const degrees = [
  { id: 1, name: 'Bachelors' },
  { id: 2, name: 'Masters' },
  { id: 3, name: 'MBA' },
  { id: 4, name: 'PhD' },
  { id: 5, name: 'PharMD' },
  { id: 6, name: 'Associates' },
]

export const months = [
  { id: 1, name: 'January' },
  { id: 2, name: 'February' },
  { id: 3, name: 'March' },
  { id: 4, name: 'April' },
  { id: 5, name: 'May' },
  { id: 6, name: 'June' },
  { id: 7, name: 'July' },
  { id: 8, name: 'August' },
  { id: 9, name: 'September' },
  { id: 10, name: 'October' },
  { id: 11, name: 'November' },
  { id: 12, name: 'December' },
]

export const startYears = [
  { id: 1, name: '1931' },
  { id: 2, name: '1932' },
  { id: 3, name: '1933' },
  { id: 4, name: '1934' },
  { id: 5, name: '1935' },
  { id: 6, name: '1936' },
  { id: 7, name: '1937' },
  { id: 8, name: '1938' },
  { id: 9, name: '1939' },
  { id: 10, name: '1940' },
  { id: 11, name: '1941' },
  { id: 12, name: '1942' },
  { id: 13, name: '1943' },
  { id: 14, name: '1944' },
  { id: 15, name: '1945' },
  { id: 16, name: '1946' },
  { id: 17, name: '1947' },
  { id: 18, name: '1948' },
  { id: 19, name: '1949' },
  { id: 20, name: '1950' },
  { id: 21, name: '1951' },
  { id: 22, name: '1952' },
  { id: 23, name: '1953' },
  { id: 24, name: '1954' },
  { id: 25, name: '1955' },
  { id: 26, name: '1956' },
  { id: 27, name: '1957' },
  { id: 28, name: '1958' },
  { id: 29, name: '1959' },
  { id: 30, name: '1960' },
  { id: 31, name: '1961' },
  { id: 32, name: '1962' },
  { id: 33, name: '1963' },
  { id: 34, name: '1964' },
  { id: 35, name: '1965' },
  { id: 36, name: '1966' },
  { id: 37, name: '1967' },
  { id: 38, name: '1968' },
  { id: 39, name: '1969' },
  { id: 40, name: '1970' },
  { id: 41, name: '1971' },
  { id: 42, name: '1972' },
  { id: 43, name: '1973' },
  { id: 44, name: '1974' },
  { id: 45, name: '1975' },
  { id: 46, name: '1976' },
  { id: 47, name: '1977' },
  { id: 48, name: '1978' },
  { id: 49, name: '1979' },
  { id: 50, name: '1980' },
  { id: 51, name: '1981' },
  { id: 52, name: '1982' },
  { id: 53, name: '1983' },
  { id: 54, name: '1984' },
  { id: 55, name: '1985' },
  { id: 56, name: '1986' },
  { id: 57, name: '1987' },
  { id: 58, name: '1988' },
  { id: 59, name: '1989' },
  { id: 60, name: '1990' },
  { id: 61, name: '1991' },
  { id: 62, name: '1992' },
  { id: 63, name: '1993' },
  { id: 64, name: '1994' },
  { id: 65, name: '1995' },
  { id: 66, name: '1996' },
  { id: 67, name: '1997' },
  { id: 68, name: '1998' },
  { id: 69, name: '1999' },
  { id: 70, name: '2000' },
  { id: 71, name: '2001' },
  { id: 72, name: '2002' },
  { id: 73, name: '2003' },
  { id: 74, name: '2004' },
  { id: 75, name: '2005' },
  { id: 76, name: '2006' },
  { id: 77, name: '2007' },
  { id: 78, name: '2008' },
  { id: 79, name: '2009' },
  { id: 80, name: '2010' },
  { id: 81, name: '2011' },
  { id: 82, name: '2012' },
  { id: 83, name: '2013' },
  { id: 84, name: '2014' },
  { id: 85, name: '2015' },
  { id: 86, name: '2016' },
  { id: 87, name: '2017' },
  { id: 88, name: '2018' },
  { id: 89, name: '2019' },
  { id: 90, name: '2020' },
  { id: 91, name: '2021' },
  { id: 92, name: '2022' },
  { id: 93, name: '2023' },
  { id: 94, name: '2024' },
  { id: 95, name: '2025' },
  { id: 96, name: '2026' },
  { id: 97, name: '2027' },
  { id: 98, name: '2028' },
  { id: 99, name: '2029' },
  { id: 100, name: '2030' },
  { id: 101, name: '2031' },
  { id: 102, name: '2032' },
  { id: 103, name: '2033' },
  { id: 104, name: '2034' },
  { id: 105, name: '2035' },
]

export const ethnicity = [
  { id: 1, name: 'Black or African American (Not Hispanic or Latino)' },
  { id: 2, name: 'Asian (Not Hispanic or Latino)' },
  { id: 3, name: 'Hispanic or Latino' },
  { id: 4, name: 'Middle Eastern' },
  { id: 5, name: 'Native Hawaiian or Other Pacific Islander (Not Hispanic or Latino)' },
  { id: 6, name: 'American Indian or Alaska Native (Not Hispanic or Latino)' },
  { id: 7, name: 'Two or More Races (Not Hispanic or Latino)' },
  { id: 8, name: 'White (Not Hispanic or Latino)' },
  { id: 9, name: 'Decline to self indentify' },
]

export const skillsOptions = [
  { value: 'abac', label: 'ABAC' },
  { value: 'accessibilitytesting', label: 'Accessibility Testing' },
  { value: 'activedirectory', label: 'Active Directory' },
  { value: 'adobexd', label: 'Adobe XD' },
  { value: 'agilemethodology', label: 'Agile Methodology' },
  { value: 'amazonredshift', label: 'Amazon Redshift (Data Warehousing)' },
  { value: 'androiddevelopment', label: 'Android Development' },
  { value: 'angular', label: 'Angular' },
  { value: 'ansible', label: 'Ansible' },
  { value: 'ansibletower', label: 'Ansible Tower' },
  { value: 'apitesting', label: 'API Testing' },
  { value: 'appium', label: 'Appium' },
  { value: 'arduino', label: 'Arduino' },
  { value: 'aspnet', label: 'ASP.NET' },
  { value: 'augmentedanalytics', label: 'Augmented Analytics' },
  { value: 'augmentedreality', label: 'Augmented Reality' },
  { value: 'autocad', label: 'AutoCAD' },
  { value: 'aws', label: 'AWS' },
  { value: 'azure', label: 'Azure' },
  { value: 'backbonejs', label: 'Backbone.js' },
  { value: 'backupandrecovery', label: 'Backup and Recovery' },
  { value: 'bash', label: 'Bash' },
  { value: 'behavior-drivendevelopment', label: 'Behavior-Driven Development' },
  { value: 'bigdata', label: 'Big Data' },
  { value: 'blackboxtesting', label: 'Black Box Testing' },
  { value: 'blender', label: 'Blender' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'blogging', label: 'Blogging' },
  { value: 'bootstrap', label: 'Bootstrap' },
  { value: 'bpmn', label: 'BPMN' },
  { value: 'burpsuite', label: 'Burp Suite' },
  { value: 'businessanalysis', label: 'Business Analysis' },
  { value: 'businessintelligence', label: 'Business Intelligence' },
  { value: 'cadcam', label: 'CAD/CAM' },
  { value: 'circleci', label: 'CircleCI' },
  { value: 'ciscosystems', label: 'Cisco Systems' },
  { value: 'cicd', label: 'CI/CD' },
  { value: 'cryptography', label: 'Cryptography' },
  { value: 'css', label: 'CSS' },
  { value: 'cucumber', label: 'Cucumber' },
  { value: 'cypress', label: 'Cypress' },
  { value: 'd3js', label: 'D3.js' },
  { value: 'django', label: 'Django' },
  { value: 'dns', label: 'DNS' },
  { value: 'docker', label: 'Docker' },
  { value: 'drupal', label: 'Drupal' },
  { value: 'elasticsearch', label: 'Elasticsearch' },
  { value: 'emberjs', label: 'Ember.js' },
  { value: 'encryption', label: 'Encryption' },
  { value: 'etl', label: 'ETL' },
  { value: 'expressjs', label: 'Express.js' },
  { value: 'figma', label: 'Figma' },
  { value: 'finalcutpro', label: 'Final Cut Pro' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'flask', label: 'Flask' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'fusion360', label: 'Fusion 360' },
  { value: 'ganttcharts', label: 'Gantt Charts' },
  { value: 'gamedevelopment', label: 'Game Development' },
  { value: 'git', label: 'Git' },
  { value: 'gitlabcicd', label: 'GitLab CI/CD' },
  { value: 'grafana', label: 'Grafana' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'grayboxtesting', label: 'Gray Box Testing' },
  { value: 'groovy', label: 'Groovy' },
  { value: 'gulp', label: 'Gulp' },
  { value: 'hadoop', label: 'Hadoop' },
  { value: 'harbor', label: 'Harbor (Container Registry)' },
  { value: 'helpdesk', label: 'Help Desk' },
  { value: 'html', label: 'HTML' },
  { value: 'hubspot', label: 'HubSpot' },
  { value: 'hyperv', label: 'Hyper-V' },
  { value: 'informationarchitecture', label: 'Information Architecture' },
  { value: 'informationsecurity', label: 'Information Security' },
  { value: 'intrusiondetectionsystems', label: 'Intrusion Detection Systems (IDS)' },
  { value: 'intrusionpreventionsystems', label: 'Intrusion Prevention Systems (IPS)' },
  { value: 'ionic', label: 'Ionic' },
  { value: 'iosdevelopment', label: 'iOS Development' },
  { value: 'iprouting', label: 'IP Routing' },
  { value: 'istqb', label: 'ISTQB' },
  { value: 'itassetmanagement', label: 'IT Asset Management' },
  { value: 'itcompliance', label: 'IT Compliance (SOX, GDPR)' },
  { value: 'itprojectmanagement', label: 'IT Project Management' },
  { value: 'itsecurity', label: 'IT Security' },
  { value: 'itservicemanagement', label: 'IT Service Management' },
  { value: 'itil', label: 'ITIL' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'jasmine', label: 'Jasmine' },
  { value: 'jenkins', label: 'Jenkins' },
  { value: 'jenkinspipeline', label: 'Jenkins Pipeline' },
  { value: 'jira', label: 'Jira' },
  { value: 'jiraservicedesk', label: 'Jira Service Desk' },
  { value: 'jmeter', label: 'JMeter' },
  { value: 'joomla', label: 'Joomla' },
  { value: 'jquery', label: 'JQuery' },
  { value: 'junit', label: 'JUnit' },
  { value: 'jwt', label: 'JWT' },
  { value: 'kafka', label: 'Kafka' },
  { value: 'kanban', label: 'Kanban' },
  { value: 'keras', label: 'Keras' },
  { value: 'kibana', label: 'Kibana' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'landingpageoptimization', label: 'Landing Page Optimization' },
  { value: 'ldap', label: 'LDAP' },
  { value: 'lean', label: 'Lean' },
  { value: 'less', label: 'LESS' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'linux', label: 'Linux' },
  { value: 'loadtesting', label: 'Load Testing' },
  { value: 'logstash', label: 'Logstash' },
  { value: 'logodesign', label: 'Logo Design' },
  { value: 'low-codenocode', label: 'Low-Code/No-Code Development' },
  { value: 'machinelearning', label: 'Machine Learning' },
  { value: 'magento', label: 'Magento' },
  { value: 'marketresearch', label: 'Market Research' },
  { value: 'matlab', label: 'MATLAB' },
  { value: 'maya', label: 'Maya' },
  { value: 'memcached', label: 'Memcached' },
  { value: 'microfrontends', label: 'Microfrontend Architecture' },
  { value: 'microservices', label: 'Microservices' },
  { value: 'microsoftdynamics365', label: 'Microsoft Dynamics 365' },
  { value: 'microsoftteams', label: 'Microsoft Teams' },
  { value: 'mocha', label: 'Mocha' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'motiongraphics', label: 'Motion Graphics' },
  { value: 'msproject', label: 'MS Project' },
  { value: 'mvc', label: 'MVC' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'nagios', label: 'Nagios' },
  { value: 'nats', label: 'NATS' },
  { value: 'naturallanguagegeneration', label: 'Natural Language Generation (NLG)' },
  { value: 'naturallanguageprocessing', label: 'Natural Language Processing' },
  { value: 'neo4j', label: 'Neo4j (Graph Database)' },
  { value: 'nessus', label: 'Nessus' },
  { value: 'netflow', label: 'NetFlow' },
  { value: 'networkarchitecture', label: 'Network Architecture' },
  { value: 'networkperformancemonitoring', label: 'Network Performance Monitoring' },
  { value: 'networksecurity', label: 'Network Security' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'nosql', label: 'NoSQL' },
  { value: 'numpy', label: 'NumPy' },
  { value: 'oauth', label: 'OAuth' },
  { value: 'octave', label: 'Octave' },
  { value: 'objective-c', label: 'Objective-C' },
  { value: 'off-pageseo', label: 'Off-Page SEO' },
  { value: 'on-pageseo', label: 'On-Page SEO' },
  { value: 'openidconnect', label: 'OpenID Connect' },
  { value: 'oracledb', label: 'Oracle DB' },
  { value: 'pandas', label: 'Pandas' },
  { value: 'penetrationtesting', label: 'Penetration Testing' },
  { value: 'perl', label: 'Perl' },
  { value: 'php', label: 'PHP' },
  { value: 'pig', label: 'Pig' },
  { value: 'plotly', label: 'Plotly' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'postman', label: 'Postman' },
  { value: 'powerbi', label: 'Power BI' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'predictiveanalytics', label: 'Predictive Analytics' },
  { value: 'premierepro', label: 'Premiere Pro' },
  { value: 'productdesign', label: 'Product Design' },
  { value: 'productlifecyclemanagement', label: 'Product Lifecycle Management' },
  { value: 'productmanagement', label: 'Product Management' },
  { value: 'productstrategy', label: 'Product Strategy' },
  { value: 'projectmanagement', label: 'Project Management' },
  { value: 'prometheus', label: 'Prometheus' },
  { value: 'prototyping', label: 'Prototyping' },
  { value: 'puppet', label: 'Puppet' },
  { value: 'puppetenterprise', label: 'Puppet Enterprise' },
  { value: 'python', label: 'Python' },
  { value: 'qtpuft', label: 'QTP/UFT' },
  { value: 'quantumcomputing', label: 'Quantum Computing' },
  { value: 'r', label: 'R' },
  { value: 'rabbitmq', label: 'RabbitMQ' },
  { value: 'react', label: 'React' },
  { value: 'reactnative', label: 'React Native' },
  { value: 'regressiontesting', label: 'Regression Testing' },
  { value: 'remotedesktoptools', label: 'Remote Desktop Tools' },
  { value: 'resourcemanagement', label: 'Resource Management' },
  { value: 'restapi', label: 'REST API' },
  { value: 'rhino', label: 'Rhino' },
  { value: 'riskassessment', label: 'Risk Assessment' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'rspec', label: 'RSpec' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'rubyonrails', label: 'Ruby on Rails' },
  { value: 'saml', label: 'SAML' },
  { value: 'sas', label: 'SAS' },
  { value: 'scala', label: 'Scala' },
  { value: 'scikitlearn', label: 'Scikit-learn' },
  { value: 'scrum', label: 'Scrum' },
  { value: 'securecodingpractices', label: 'Secure Coding Practices' },
  { value: 'securityawarenesstraining', label: 'Security Awareness Training' },
  {
    value: 'securitycertifications',
    label: 'Security Certifications (CISSP, CISM, CompTIA Security+)',
  },
  { value: 'siem', label: 'Security Information and Event Management (SIEM)' },
  { value: 'seo', label: 'SEO' },
  { value: 'serverlessarchitecture', label: 'Serverless Architecture' },
  { value: 'serverlesscomputing', label: 'Serverless Computing' },
  { value: 'servicemesh', label: 'Service Mesh (e.g., Istio, Linkerd)' },
  { value: 'servicenow', label: 'ServiceNow' },
  { value: 'shellscripting', label: 'Shell Scripting' },
  { value: 'sketch', label: 'Sketch' },
  { value: 'sketchup', label: 'SketchUp' },
  { value: 'slack', label: 'Slack' },
  { value: 'smartcontracts', label: 'Smart Contracts' },
  { value: 'soap', label: 'SOAP' },
  { value: 'solidity', label: 'Solidity' },
  { value: 'spss', label: 'SPSS' },
  { value: 'spring', label: 'Spring' },
  { value: 'springboot', label: 'Spring Boot' },
  { value: 'sql', label: 'SQL' },
  { value: 'sqlite', label: 'SQLite' },
  { value: 'squarespace', label: 'Squarespace' },
  { value: 'ssh', label: 'SSH' },
  { value: 'stakeholderanalysis', label: 'Stakeholder Analysis' },
  { value: 'stakeholdermanagement', label: 'Stakeholder Management' },
  { value: 'stata', label: 'Stata' },
  { value: 'staticcodeanalysis', label: 'Static Code Analysis' },
  { value: 'storagesystems', label: 'Storage Systems (SAN, NAS)' },
  { value: 'struts', label: 'Struts' },
  { value: 'swagger', label: 'Swagger' },
  { value: 'swift', label: 'Swift' },
  { value: 'systemmonitoring', label: 'System Monitoring (Nagios, Zabbix)' },
  { value: 'tableau', label: 'Tableau' },
  { value: 'tailwindcss', label: 'Tailwind CSS' },
  { value: 'tcpip', label: 'TCP/IP' },
  { value: 'technicalseo', label: 'Technical SEO' },
  { value: 'tensorflow', label: 'TensorFlow' },
  { value: 'testcasemanagement', label: 'Test Case Management (Zephyr, TestRail)' },
  { value: 'testdrivendevelopment', label: 'Test-Driven Development' },
  { value: 'testng', label: 'TestNG' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'ubuntu', label: 'Ubuntu' },
  { value: 'uidesign', label: 'UI Design' },
  { value: 'unity', label: 'Unity' },
  { value: 'unix', label: 'Unix' },
  { value: 'usabilitytesting', label: 'Usability Testing' },
  { value: 'userexperience', label: 'User Experience (UX) Design' },
  { value: 'userinterface', label: 'User Interface (UI) Design' },
  { value: 'userresearch', label: 'User Research' },
  { value: 'userstories', label: 'User Stories' },
  { value: 'vault', label: 'Vault (Secret Management)' },
  { value: 'virtualreality', label: 'Virtual Reality' },
  { value: 'visualdesign', label: 'Visual Design' },
  { value: 'voip', label: 'VoIP' },
  { value: 'vuejs', label: 'Vue.js' },
  { value: 'waterfallmethodology', label: 'Waterfall Methodology' },
  { value: 'webanalytics', label: 'Web Analytics' },
  { value: 'webdesign', label: 'Web Design' },
  { value: 'websockets', label: 'Web Sockets' },
  { value: 'webpack', label: 'Webpack' },
  { value: 'wireshark', label: 'Wireshark' },
  { value: 'wix', label: 'Wix' },
  { value: 'wireframing', label: 'Wireframing' },
  { value: 'wirelessnetworking', label: 'Wireless Networking' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'wsfederation', label: 'WS-Federation' },
  { value: 'wssecurity', label: 'WS-Security' },
  { value: 'wstrust', label: 'WS-Trust' },
  { value: 'xml', label: 'XML' },
  { value: 'xmlencryption', label: 'XML Encryption' },
  { value: 'xmlsignature', label: 'XML Signature' },
  { value: 'xamarin', label: 'Xamarin' },
  { value: 'xacml', label: 'XACML' },
  { value: 'yii', label: 'Yii' },
  { value: 'youtubeads', label: 'YouTube Ads' },
  { value: 'zendesk', label: 'Zendesk' },
  { value: 'zohocrm', label: 'Zoho CRM' },
  { value: 'zookeeper', label: 'Zookeeper' },
  { value: 'zap', label: 'Zap' },
]

// The array contains objects for each skill, where 'value' is in lower case and 'label' is in sentence case.

export const countryCodes = [
  { label: 'ZZ', name: 'International', flag: 'zz' },
  { label: 'AF', name: 'Afghanistan', flag: 'af' },
  { label: 'AX', name: 'Åland Islands', flag: 'ax' },
  { label: 'AL', name: 'Albania', flag: 'al' },
  { label: 'DZ', name: 'Algeria', flag: 'dz' },
  { label: 'AS', name: 'American Samoa', flag: 'as' },
  { label: 'AD', name: 'Andorra', flag: 'ad' },
  { label: 'AO', name: 'Angola', flag: 'ao' },
  { label: 'AI', name: 'Anguilla', flag: 'ai' },
  { label: 'AG', name: 'Antigua and Barbuda', flag: 'ag' },
  { label: 'AR', name: 'Argentina', flag: 'ar' },
  { label: 'AM', name: 'Armenia', flag: 'am' },
  { label: 'AW', name: 'Aruba', flag: 'aw' },
  { label: 'AC', name: 'Ascension Island', flag: 'ac' },
  { label: 'AU', name: 'Australia', flag: 'au' },
  { label: 'AT', name: 'Austria', flag: 'at' },
  { label: 'AZ', name: 'Azerbaijan', flag: 'az' },
  { label: 'BS', name: 'Bahamas', flag: 'bs' },
  { label: 'BH', name: 'Bahrain', flag: 'bh' },
  { label: 'BD', name: 'Bangladesh', flag: 'bd' },
  { label: 'BB', name: 'Barbados', flag: 'bb' },
  { label: 'BY', name: 'Belarus', flag: 'by' },
  { label: 'BE', name: 'Belgium', flag: 'be' },
  { label: 'BZ', name: 'Belize', flag: 'bz' },
  { label: 'BJ', name: 'Benin', flag: 'bj' },
  { label: 'BM', name: 'Bermuda', flag: 'bm' },
  { label: 'BT', name: 'Bhutan', flag: 'bt' },
  { label: 'BO', name: 'Bolivia', flag: 'bo' },
  { label: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: 'bq' },
  { label: 'BA', name: 'Bosnia and Herzegovina', flag: 'ba' },
  { label: 'BW', name: 'Botswana', flag: 'bw' },
  { label: 'BR', name: 'Brazil', flag: 'br' },
  { label: 'IO', name: 'British Indian Ocean Territory', flag: 'io' },
  { label: 'BN', name: 'Brunei Darussalam', flag: 'bn' },
  { label: 'BG', name: 'Bulgaria', flag: 'bg' },
  { label: 'BF', name: 'Burkina Faso', flag: 'bf' },
  { label: 'BI', name: 'Burundi', flag: 'bi' },
  { label: 'KH', name: 'Cambodia', flag: 'kh' },
  { label: 'CM', name: 'Cameroon', flag: 'cm' },
  { label: 'CA', name: 'Canada', flag: 'ca' },
  { label: 'CV', name: 'Cape Verde', flag: 'cv' },
  { label: 'KY', name: 'Cayman Islands', flag: 'ky' },
  { label: 'CF', name: 'Central African Republic', flag: 'cf' },
  { label: 'TD', name: 'Chad', flag: 'td' },
  { label: 'CL', name: 'Chile', flag: 'cl' },
  { label: 'CN', name: 'China', flag: 'cn' },
  { label: 'CX', name: 'Christmas Island', flag: 'cx' },
  { label: 'CC', name: 'Cocos (Keeling) Islands', flag: 'cc' },
  { label: 'CO', name: 'Colombia', flag: 'co' },
  { label: 'KM', name: 'Comoros', flag: 'km' },
  { label: 'CG', name: 'Congo', flag: 'cg' },
  { label: 'CD', name: 'Congo, Democratic Republic of the', flag: 'cd' },
  { label: 'CK', name: 'Cook Islands', flag: 'ck' },
  { label: 'CR', name: 'Costa Rica', flag: 'cr' },
  { label: 'CI', name: "Cote d'Ivoire", flag: 'ci' },
  { label: 'HR', name: 'Croatia', flag: 'hr' },
  { label: 'CU', name: 'Cuba', flag: 'cu' },
  { label: 'CW', name: 'Curaçao', flag: 'cw' },
  { label: 'CY', name: 'Cyprus', flag: 'cy' },
  { label: 'CZ', name: 'Czech Republic', flag: 'cz' },
  { label: 'DK', name: 'Denmark', flag: 'dk' },
  { label: 'DJ', name: 'Djibouti', flag: 'dj' },
  { label: 'DM', name: 'Dominica', flag: 'dm' },
  { label: 'DO', name: 'Dominican Republic', flag: 'do' },
  { label: 'EC', name: 'Ecuador', flag: 'ec' },
  { label: 'EG', name: 'Egypt', flag: 'eg' },
  { label: 'SV', name: 'El Salvador', flag: 'sv' },
  { label: 'GQ', name: 'Equatorial Guinea', flag: 'gq' },
  { label: 'ER', name: 'Eritrea', flag: 'er' },
  { label: 'EE', name: 'Estonia', flag: 'ee' },
  { label: 'ET', name: 'Ethiopia', flag: 'et' },
  { label: 'FK', name: 'Falkland Islands', flag: 'fk' },
  { label: 'FO', name: 'Faroe Islands', flag: 'fo' },
  { label: 'FM', name: 'Federated States of Micronesia', flag: 'fm' },
  { label: 'FJ', name: 'Fiji', flag: 'fj' },
  { label: 'FI', name: 'Finland', flag: 'fi' },
  { label: 'FR', name: 'France', flag: 'fr' },
  { label: 'GF', name: 'French Guiana', flag: 'gf' },
  { label: 'PF', name: 'French Polynesia', flag: 'pf' },
  { label: 'GA', name: 'Gabon', flag: 'ga' },
  { label: 'GM', name: 'Gambia', flag: 'gm' },
  { label: 'GE', name: 'Georgia', flag: 'ge' },
  { label: 'DE', name: 'Germany', flag: 'de' },
  { label: 'GH', name: 'Ghana', flag: 'gh' },
  { label: 'GI', name: 'Gibraltar', flag: 'gi' },
  { label: 'GR', name: 'Greece', flag: 'gr' },
  { label: 'GL', name: 'Greenland', flag: 'gl' },
  { label: 'GD', name: 'Grenada', flag: 'gd' },
  { label: 'GP', name: 'Guadeloupe', flag: 'gp' },
  { label: 'GU', name: 'Guam', flag: 'gu' },
  { label: 'GT', name: 'Guatemala', flag: 'gt' },
  { label: 'GG', name: 'Guernsey', flag: 'gg' },
  { label: 'GN', name: 'Guinea', flag: 'gn' },
  { label: 'GW', name: 'Guinea-Bissau', flag: 'gw' },
  { label: 'GY', name: 'Guyana', flag: 'gy' },
  { label: 'HT', name: 'Haiti', flag: 'ht' },
  { label: 'VA', name: 'Holy See (Vatican City State)', flag: 'va' },
  { label: 'HN', name: 'Honduras', flag: 'hn' },
  { label: 'HK', name: 'Hong Kong', flag: 'hk' },
  { label: 'HU', name: 'Hungary', flag: 'hu' },
  { label: 'IS', name: 'Iceland', flag: 'is' },
  { label: 'IN', name: 'India', flag: 'in' },
  { label: 'ID', name: 'Indonesia', flag: 'id' },
  { label: 'IR', name: 'Iran', flag: 'ir' },
  { label: 'IQ', name: 'Iraq', flag: 'iq' },
  { label: 'IE', name: 'Ireland', flag: 'ie' },
  { label: 'IM', name: 'Isle of Man', flag: 'im' },
  { label: 'IL', name: 'Israel', flag: 'il' },
  { label: 'IT', name: 'Italy', flag: 'it' },
  { label: 'JM', name: 'Jamaica', flag: 'jm' },
  { label: 'JP', name: 'Japan', flag: 'jp' },
  { label: 'JE', name: 'Jersey', flag: 'je' },
  { label: 'JO', name: 'Jordan', flag: 'jo' },
  { label: 'KZ', name: 'Kazakhstan', flag: 'kz' },
  { label: 'KE', name: 'Kenya', flag: 'ke' },
  { label: 'KI', name: 'Kiribati', flag: 'ki' },
  { label: 'XK', name: 'Kosovo', flag: 'xk' },
  { label: 'KW', name: 'Kuwait', flag: 'kw' },
  { label: 'KG', name: 'Kyrgyzstan', flag: 'kg' },
  { label: 'LA', name: 'Laos', flag: 'la' },
  { label: 'LV', name: 'Latvia', flag: 'lv' },
  { label: 'LB', name: 'Lebanon', flag: 'lb' },
  { label: 'LS', name: 'Lesotho', flag: 'ls' },
  { label: 'LR', name: 'Liberia', flag: 'lr' },
  { label: 'LY', name: 'Libya', flag: 'ly' },
  { label: 'LI', name: 'Liechtenstein', flag: 'li' },
  { label: 'LT', name: 'Lithuania', flag: 'lt' },
  { label: 'LU', name: 'Luxembourg', flag: 'lu' },
  { label: 'MO', name: 'Macao', flag: 'mo' },
  { label: 'MG', name: 'Madagascar', flag: 'mg' },
  { label: 'MW', name: 'Malawi', flag: 'mw' },
  { label: 'MY', name: 'Malaysia', flag: 'my' },
  { label: 'MV', name: 'Maldives', flag: 'mv' },
  { label: 'ML', name: 'Mali', flag: 'ml' },
  { label: 'MT', name: 'Malta', flag: 'mt' },
  { label: 'MH', name: 'Marshall Islands', flag: 'mh' },
  { label: 'MQ', name: 'Martinique', flag: 'mq' },
  { label: 'MR', name: 'Mauritania', flag: 'mr' },
  { label: 'MU', name: 'Mauritius', flag: 'mu' },
  { label: 'YT', name: 'Mayotte', flag: 'yt' },
  { label: 'MX', name: 'Mexico', flag: 'mx' },
  { label: 'MD', name: 'Moldova', flag: 'md' },
  { label: 'MC', name: 'Monaco', flag: 'mc' },
  { label: 'MN', name: 'Mongolia', flag: 'mn' },
  { label: 'ME', name: 'Montenegro', flag: 'me' },
  { label: 'MS', name: 'Montserrat', flag: 'ms' },
  { label: 'MA', name: 'Morocco', flag: 'ma' },
  { label: 'MZ', name: 'Mozambique', flag: 'mz' },
  { label: 'MM', name: 'Myanmar', flag: 'mm' },
  { label: 'NA', name: 'Namibia', flag: 'na' },
  { label: 'NR', name: 'Nauru', flag: 'nr' },
  { label: 'NP', name: 'Nepal', flag: 'np' },
  { label: 'NL', name: 'Netherlands', flag: 'nl' },
  { label: 'NC', name: 'New Caledonia', flag: 'nc' },
  { label: 'NZ', name: 'New Zealand', flag: 'nz' },
  { label: 'NI', name: 'Nicaragua', flag: 'ni' },
  { label: 'NE', name: 'Niger', flag: 'ne' },
  { label: 'NG', name: 'Nigeria', flag: 'ng' },
  { label: 'NU', name: 'Niue', flag: 'nu' },
  { label: 'NF', name: 'Norfolk Island', flag: 'nf' },
  { label: 'KP', name: 'North Korea', flag: 'kp' },
  { label: 'MK', name: 'North Macedonia', flag: 'mk' },
  { label: 'MP', name: 'Northern Mariana Islands', flag: 'mp' },
  { label: 'NO', name: 'Norway', flag: 'no' },
  { label: 'OM', name: 'Oman', flag: 'om' },
  { label: 'PK', name: 'Pakistan', flag: 'pk' },
  { label: 'PW', name: 'Palau', flag: 'pw' },
  { label: 'PS', name: 'Palestine', flag: 'ps' },
  { label: 'PA', name: 'Panama', flag: 'pa' },
  { label: 'PG', name: 'Papua New Guinea', flag: 'pg' },
  { label: 'PY', name: 'Paraguay', flag: 'py' },
  { label: 'PE', name: 'Peru', flag: 'pe' },
  { label: 'PH', name: 'Philippines', flag: 'ph' },
  { label: 'PL', name: 'Poland', flag: 'pl' },
  { label: 'PT', name: 'Portugal', flag: 'pt' },
  { label: 'PR', name: 'Puerto Rico', flag: 'pr' },
  { label: 'QA', name: 'Qatar', flag: 'qa' },
  { label: 'RE', name: 'Reunion', flag: 're' },
  { label: 'RO', name: 'Romania', flag: 'ro' },
  { label: 'RU', name: 'Russia', flag: 'ru' },
  { label: 'RW', name: 'Rwanda', flag: 'rw' },
  { label: 'BL', name: 'Saint Barthélemy', flag: 'bl' },
  { label: 'SH', name: 'Saint Helena', flag: 'sh' },
  { label: 'KN', name: 'Saint Kitts and Nevis', flag: 'kn' },
  { label: 'LC', name: 'Saint Lucia', flag: 'lc' },
  { label: 'MF', name: 'Saint Martin (French Part)', flag: 'mf' },
  { label: 'PM', name: 'Saint Pierre and Miquelon', flag: 'pm' },
  { label: 'VC', name: 'Saint Vincent and the Grenadines', flag: 'vc' },
  { label: 'WS', name: 'Samoa', flag: 'ws' },
  { label: 'SM', name: 'San Marino', flag: 'sm' },
  { label: 'ST', name: 'Sao Tome and Principe', flag: 'st' },
  { label: 'SA', name: 'Saudi Arabia', flag: 'sa' },
  { label: 'SN', name: 'Senegal', flag: 'sn' },
  { label: 'RS', name: 'Serbia', flag: 'rs' },
  { label: 'SC', name: 'Seychelles', flag: 'sc' },
  { label: 'SL', name: 'Sierra Leone', flag: 'sl' },
  { label: 'SG', name: 'Singapore', flag: 'sg' },
  { label: 'SX', name: 'Sint Maarten', flag: 'sx' },
  { label: 'SK', name: 'Slovakia', flag: 'sk' },
  { label: 'SI', name: 'Slovenia', flag: 'si' },
  { label: 'SB', name: 'Solomon Islands', flag: 'sb' },
  { label: 'SO', name: 'Somalia', flag: 'so' },
  { label: 'ZA', name: 'South Africa', flag: 'za' },
  { label: 'KR', name: 'South Korea', flag: 'kr' },
  { label: 'SS', name: 'South Sudan', flag: 'ss' },
  { label: 'ES', name: 'Spain', flag: 'es' },
  { label: 'LK', name: 'Sri Lanka', flag: 'lk' },
  { label: 'SD', name: 'Sudan', flag: 'sd' },
  { label: 'SR', name: 'Suriname', flag: 'sr' },
  { label: 'SJ', name: 'Svalbard and Jan Mayen', flag: 'sj' },
  { label: 'SZ', name: 'Swaziland', flag: 'sz' },
  { label: 'SE', name: 'Sweden', flag: 'se' },
  { label: 'CH', name: 'Switzerland', flag: 'ch' },
  { label: 'SY', name: 'Syria', flag: 'sy' },
  { label: 'TW', name: 'Taiwan', flag: 'tw' },
  { label: 'TJ', name: 'Tajikistan', flag: 'tj' },
  { label: 'TZ', name: 'Tanzania', flag: 'tz' },
  { label: 'TH', name: 'Thailand', flag: 'th' },
  { label: 'TL', name: 'Timor-Leste', flag: 'tl' },
  { label: 'TG', name: 'Togo', flag: 'tg' },
  { label: 'TK', name: 'Tokelau', flag: 'tk' },
  { label: 'TO', name: 'Tonga', flag: 'to' },
  { label: 'TT', name: 'Trinidad and Tobago', flag: 'tt' },
  { label: 'TA', name: 'Tristan da Cunha', flag: 'ta' },
  { label: 'TN', name: 'Tunisia', flag: 'tn' },
  { label: 'TR', name: 'Turkey', flag: 'tr' },
  { label: 'TM', name: 'Turkmenistan', flag: 'tm' },
  { label: 'TC', name: 'Turks and Caicos Islands', flag: 'tc' },
  { label: 'TV', name: 'Tuvalu', flag: 'tv' },
  { label: 'UG', name: 'Uganda', flag: 'ug' },
  { label: 'UA', name: 'Ukraine', flag: 'ua' },
  { label: 'AE', name: 'United Arab Emirates', flag: 'ae' },
  { label: 'GB', name: 'United Kingdom', flag: 'gb' },
  { label: 'US', name: 'United States', flag: 'us' },
  { label: 'UY', name: 'Uruguay', flag: 'uy' },
  { label: 'UZ', name: 'Uzbekistan', flag: 'uz' },
  { label: 'VU', name: 'Vanuatu', flag: 'vu' },
  { label: 'VE', name: 'Venezuela', flag: 've' },
  { label: 'VN', name: 'Vietnam', flag: 'vn' },
  { label: 'WF', name: 'Wallis and Futuna', flag: 'wf' },
  { label: 'EH', name: 'Western Sahara', flag: 'eh' },
  { label: 'YE', name: 'Yemen', flag: 'ye' },
  { label: 'ZM', name: 'Zambia', flag: 'zm' },
  { label: 'ZW', name: 'Zimbabwe', flag: 'zw' },
]

export const tabs = [
  { id: 1, name: 'Personal', slug: 'personal' },
  { id: 2, name: 'Education', slug: 'education' },
  { id: 3, name: 'Work Experience', slug: 'work-experience' },
  { id: 4, name: 'Work Auth', slug: 'work-authorization' },
  { id: 5, name: 'Ethnicity', slug: 'ethnicity' },
  { id: 6, name: 'Skills', slug: 'skills' },
  { id: 7, name: 'Projects', slug: 'projects' },
  { id: 8, name: 'Socials', slug: 'socials' },
]

export const experienceTypes = [
  { id: 1, name: 'Full time' },
  { id: 2, name: 'Part time' },
  { id: 3, name: 'Internship' },
]
