export const JobViteConfig = {
  key: 'jobvite',
  regex: /^https:\/\/jobs\.jobvite\.com\/[a-zA-Z\-]+\/job\/[a-zA-Z0-9]+(\/apply)?/,
  commonSelector: `div[ng-form="inputForm"] input[type="radio"],div[ng-form="inputForm"] input[type="text"], div[ng-form="inputForm"] input[type="tel"]`,
  selectors: {
    firstName: 'First Name|Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    linkedIn_url: `LinkedIn`,
    github_url: `GitHub`,
    portfolio_url: `Portfolio`,
    description: 'Description',
    position_title: 'Title',
    school_name: 'School',
    degree: 'Degree',
    major: 'Major',
    other_url: `Other`,
    is_authorized_in_us: 'authorized to work|eligible to work',
    is_required_visa: 'visa',
    secondary_email: `Email Address`,
    secondary_phone: 'Phone Number',
    city: `City`,
    gender: `Gender`,
    ethnicity: `race`,
    is_veteran: 'veteran',
  },
}
